{% set name = "orange-widget-base" %}
{% set version = "4.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 178ae4cce0cfa6229ff68b47b19ef51a46c4c1633cdc3b8271766de866bfa42f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar >=0.3.3
  run:
    - python
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.2a.dev0,<0.3a
    - typing_extensions >=3.7.4.3
    - appnope  # [osx]
  run_constrained:
    # pyqt required due to transient dependcies pulled. This is a workaround.
    - pyqt <= 6.0.0

{% set skip_tests = "" %}
# Various tests breaks on CI due to lack of UI (headless) - Skip failing tests. 
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_widget.py::test_store_restore_layout_geom" %}
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_widget.py::test_menu" %}
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_gui.py::test_set_datetime" %}

{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_widget.py::TestWidgetMenu::test_menu" %}                # [win]
{% set skip_tests = skip_tests + " --ignore=orangewidget/tests/test_control_getter.py" %}                                     # [linux]
{% set skip_tests = skip_tests + " --ignore=orangewidget/tests/test_io.py" %}                                                 # [linux]
{% set skip_tests = skip_tests + " --ignore=orangewidget/tests/test_matplotlib_export.py" %}                                  # [linux]
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_control_getter.py::ControlGetterTests::test_getter" %}  # [linux or osx]
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_io.py::TestIO::test_pdf" %}                             # [linux or osx]
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_io.py::TestPdf::test_other" %}                          # [linux or osx]
{% set skip_tests = skip_tests + " --deselect=orangewidget/tests/test_io.py::TestPdf::test_pyqtgraph" %}                      # [linux or osx]
{% set skip_tests = skip_tests + " --ignore=orangewidget/tests/test_gui.py" %}                                                # [linux or osx]
{% set skip_tests = skip_tests + " --ignore=orangewidget/tests/test_widget.py" %}                                             # [linux or osx]

test:
  imports:
    - orangewidget.gui
    - orangewidget.widget
    - orangewidget.io  # [linux]
  source_files:
    - orangewidget/tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest {{ skip_tests }} orangewidget/tests -v

about:
  home: https://orangedatamining.com
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Core component of Orange Canvas
  description: Orange Canvas Core is a framework for building graphical user interfaces for editing workflows. It is a component used to build the Orange Canvas data-mining application (for which it was developed in the first place).
  doc_url: https://orange-widget-base.readthedocs.io
  dev_url: https://github.com/biolab/orange-widget-base

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
