{% set name = "orange-widget-base" %}
{% set version = "4.27.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c8ecbc018111673223a1b8b61d4c9f14b9ba6b3e980ad38ff3188889cadb5d88

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar >=0.3.3
  run:
    - python
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - typing_extensions >=3.7.4.3
    - orange-canvas-core >=0.2a.dev0,<0.3a
    - appnope  # [osx]
  run_constrained:
    # pyqt required due to transient dependcies pulled. This is a workaround.
    - pyqt <=6.0.0

# >   self.assertTrue(timer.isActive())
# E   AssertionError: False is not true
{% set deselect_tests = " --deselect=test_widget.py::TestWidgetMenu::test_menu" %}
# >   self.assertGreater(os.path.getsize(fname), size_empty + 600)
# E   AssertionError: 8132 not greater than 8668
{% set deselect_tests = deselect_tests + " --deselect=test_io.py::TestPdf::test_pyqtgraph" %}  # [linux]
test:
  imports:
    - orangewidget.gui
    - orangewidget.widget
    - orangewidget.io  # [linux]
  commands:
    - pip check
    - export QT_QPA_PLATFORM=offscreen  # [unix]
    - pytest --pyargs orangewidget.tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://orangedatamining.com
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Core component of Orange Canvas
  description: Orange Canvas Core is a framework for building graphical user interfaces for editing workflows. It is a component used to build the Orange Canvas data-mining application (for which it was developed in the first place).
  doc_url: https://orange-widget-base.readthedocs.io
  dev_url: https://github.com/biolab/orange-widget-base

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
