{% set name = "orange-widget-base" %}
{% set version = "4.19.0" %}

# on our linux builders there is no X11 installed and therefore import
# test will fail
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
{% set enable_testingui = true %}
{% else %}
{% set enable_testingui = false %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 193055dbee8701ad62d5471c5287b092ce53bb77f7f810ec68bf96816f6acaa2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<36]
  skip: True  # [linux and (s390x or ppc64le)]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.1.28,<0.2a
    - typing_extensions >=3.7.4.3
    # appnope is skipped here since if we add it package is not noarch: python anymore
    # and appnope is used just optionally in tests

{% if enable_testingui %}
test:
  imports:
    - orangewidget.widget
    - orangewidget.gui
{% endif %}

about:
  home: https://github.com/biolab/orange-widget-base
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Base Widget for Orange Canvas

  description: |
    This project implements the base OWBaseWidget class and utilities for use
    in Orange Canvas workflows.

  doc_url: https://orange-widget-base.readthedocs.io/
  dev_url: https://github.com/biolab/orange-widget-base/

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
