{% set name = "orange-widget-base" %}
{% set version = "4.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 178ae4cce0cfa6229ff68b47b19ef51a46c4c1633cdc3b8271766de866bfa42f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar >=0.3.3
  run:
    - python
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.2a.dev0,<0.3a
    - typing_extensions >=3.7.4.3
    - appnope  # [osx]
  run_constrained:
    - pyqt <= 6.0.0
  # pyqt required due to transient dependcies pulled. This is a workaround.

# on our linux builders there is no X11 installed and therefore import
# test will fail
test:
  imports:
    - orangewidget.gui  # [win or osx]
    - orangewidget.io  # [linux]
  source_files:
    - orangewidget/tests  # [win or osx]
  requires:
    - pip
    - pytest  # [win or osx]
  commands:
    - pip check
    - pytest -k "not (test_store_restore_layout_geom or test_set_datetime or test_menu)" orangewidget/tests -v  # [win or (osx and arm64)]

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Base Widget for Orange Canvas
  description: |
    This project implements the base OWBaseWidget class and utilities for use
    in Orange Canvas workflows.
  doc_url: https://orange-widget-base.readthedocs.io/
  dev_url: https://github.com/biolab/orange-widget-base/

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
