{% set name = "orange-widget-base" %}
{% set version = "4.25.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 14a42660ed832523b197f3d27aa2193d2f8213732d427b74bbe6401e9fe01ba6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [py<39 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar
  run:
    - python
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.2a.dev0,<0.3a
    - typing_extensions >=3.7.4.3
    - importlib_resources  # [py<310]
    - importlib_metadata
    - appnope  # [osx]
  # importlib_metadata is not mentioned in the setup.py, but is called by runtime.
  run_constrained:
    - pyqt <= 6.0.0
  # pyqt required due to transient dependcies pulled. This is a workaround.

# on our linux builders there is no X11 installed and therefore import
# test will fail
test:
  imports:
    - orangewidget.gui  # [win or osx]
    - orangewidget.io  # [linux]
  source_files:
    - orangewidget/tests  # [win or osx]
  requires:
    - pip
    - pytest  # [win or osx]
  commands:
    - pip check
    - pytest -k "not test_store_restore_layout_geom" orangewidget/tests -v  # [win or (osx or arm64)]

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Base Widget for Orange Canvas
  description: |
    This project implements the base OWBaseWidget class and utilities for use
    in Orange Canvas workflows.
  doc_url: https://orange-widget-base.readthedocs.io/
  dev_url: https://github.com/biolab/orange-widget-base/

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
